name: fastai
channels:
  - conda-forge
  - pytorch
  - fastai
  - defaults
dependencies:
  - pytorch>=1.3.0
  - torchvision>=0.5
  - matplotlib
  - cuda92
  - fastprogress>=0.1.22
  - fastai
  - jupyter
  - jupyterlab
  - pandas
  - requests
  - pyyaml
  - pillow
  - python>=3.6
  - pip
  - scikit-learn
  - scipy
  - spacy
  - graphviz
  - graphite2
  - pip:
      - nvidia-ml-py3
      - dataclasses
      - fastbook
      - fastprocess
      - fastai2
      - utils
      - graphviz
      - ipywidgets>=7.5.1
      - nbdev
      - azure-cognitiveservices-search-imagesearch
